version: 2.0
jobs:
  build:
    docker:
      - image: yukijs/rust-os:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "Cargo.toml" }}
      - run:
          name: "make"
          command: |
            make
      - save_cache:
          paths:
            - target/
            - ~/.cargo
          key: cache-{{ checksum "Cargo.toml" }}
      - store_artifacts:
          path: build/haribote.img
          destination: haribote.img